---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: muppet-server
  namespace: dev
  labels:
    app: muppet-server
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: muppet-server
  template:
    metadata:
      labels:
        app: muppet-server
    spec:
      containers:
      - name: muppet-server
        image: ghcr.io/red-avtovo/muppet:sha-sha_short
        imagePullPolicy: Always
        ports:
        - containerPort: 8765
          name: websocket
        envFrom:
        - secretRef:
            name: muppet-secrets
        - configMapRef:
            name: muppet-config
        resources:
          limits:
            cpu: "0.5"
            memory: "256Mi"
          requests:
            cpu: "0.2"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: muppet-server
  namespace: dev
spec:
  selector:
    app: muppet-server
  ports:
  - port: 8765
    targetPort: 8765
    name: websocket
  type: NodePort